angular.module('lifestyleApp', []).controller('ArticleController', function ($scope, $location) {

  const articles = {
    1: {
      title: "The Importance of Sports to Health and Fitness",
      image: "https://thehealthcareinsights.com/wp-content/uploads/2022/10/The-Importance-of-Sports-to-Health-and-Fitness.jpg",
      content: [
        { type: "text", value: "Playing sports is a great way to improve one’s health and fitness. Sports have a huge impact on a person’s daily life and health. Sometimes it’s difficult to muster the motivation to spend hours on a treadmill to lose stubborn fat. Still, an invitation to participate in an exciting sport would motivate you to get moving." },
        { type: "text", value: "I agree that participating in sports shouldn’t be viewed as a replacement for exercise, but doing so can help you stay on top of your health and fitness." },
        { type: "text", value: "Indulging in physical activity like sports improves your heart function, reduces the risks of diabetes, lowers tension and stress, and controls blood sugar." },
        { type: "text", value: "Playing sports helps you build muscles and improves your coordination and muscle memory." },
        { type: "heading", value: "1. Playing Sports Makes You Happier" },
        { type: "text", value: "Life is difficult, and positive and negative emotions are constantly around us. Many people cope with difficult situations by binge-watching television, overeating, or working on themselves." },
        { type: "text", value: "One way to boost your mood, feel better about yourself, and reduce stress, anxiety, and depression is to exercise. Sporting activity promotes changes in the area of the brain that controls anxiety and stress." },
        { type: "text", value: "Sporting activities increase serotonin and norepinephrine sensitivity in the brain, which relieves depression."},
        { type: "text", value:  "Sporting activities increase serotonin and norepinephrine sensitivity in the brain, which relieves depression."},
        { type: "text", value: "If you want to trigger positive feelings, playing sports is the best option as it stimulates the production of endorphins and reduces your perception of pain."},
        { type: "text", value:  "Any sport that you enjoy and find enjoyable can help you combat anxiety, and in general, it will make you happier and more content with life."},
        { type: "heading", value: "2. Sports are a Fun Way to Lose Weight" },
        { type: "text", value: "The obesity epidemic affects millions of people worldwide, and our current way of life is to blame. We spend 9 to 10 hours a day in a cubicle at work, then return home worn out to eat whatever is on the table. This routine increases your chances of gaining weight and thus leads to hypertension and heart disease." },
        { type: "text", value: "Remember that excess body fat contributes to obesity and that working out can lower body fat. The only issue with exercising is that it wears you out and overwhelms you because of the difficult and heavy weight lifting that goes into it. " },
        { type: "text", value: "porting activities are enjoyable, in contrast to working out in a gym. The magic of playing sports is that you are excited, thrilled, and motivated to continue playing even when you are exhausted." },
        { type: "heading", value: "3. Helps to maintain your mental health " },
        { type: "text", value: "Stress is a part of every working individual out there in the world. Everyone, whether they are employed or not, experiences stress daily. Playing a sports activity can help you reduce stress in your life." },
        { type: "text", value: "Playing sports increases your heart rate and improves blood flow to your brain. This, in turn, stimulates the production of hormones that activate the growth of brain cells." },
        { type: "heading", value: "4. Sports Helps in improving Sleep Quality" },
        { type: "text", value: "Playing sports increases your heart rate and improves blood flow to your brain. This, in turn, stimulates the production of hormones that activate the growth of brain cells." },
        { type: "text", value: "Exercise raises body temperature, improving sleep quality by lowering body temperature while sleeping. According to studies, exercising for at least 150 minutes a week can improve the quality of your sleep by up to 65%." },
        { type: "heading", value: "5. Helps in Muscle Training" },
        { type: "text", value: "Playing sports is one of the best ways to have a proper muscle workout. It is enjoyable to play sports as it does not feel like a chore, and at the same time, they give you strong and toned muscles. You can tone your muscles by regularly playing basketball, soccer, football, tennis and baseball." },
        { type: "text", value: "By playing sports, you gain lean muscle mass and burn fat simultaneously. For gaining toned muscles, you must prefer sports that involve the movement of most of your muscle groups." },
        { type: "heading", value: "Closing thoughts" },
        { type: "text", value: "There are more health and fitness benefits of sports, such as sport pushes you to challenge yourself, it exposes you to the highs and lows of losing and winning a game, improves your balance and reduces the risk of falls, and overall sports can help you to feel good about yourself." },
        { type: "text", value: "Sports are a good way to take care of yourself, and I highly recommend you play at least a game you love the most twice a week." },
      ]
    },
    2: {
      title: "Pentingnya Olahraga untuk Kesehatan Optimal",
      image: "https://sarolangunkab.go.id/storage/berita/eeac7dc21ceff5295df7b2b0ae9dff50.jpg",
      content: [
        { type: "text", value: "Olahraga merupakan bagian integral dari gaya hidup sehat yang memberikan manfaat tak terbantahkan bagi kesehatan fisik dan mental. Melakukan olahraga secara teratur dapat membantu menjaga kesehatan secara optimal dan meningkatkan kualitas hidup. " },
        { type: "text", value: "Dalam artikel ini, kita akan menjelajahi pentingnya olahraga dalam menjaga kesehatan secara menyeluruh serta memberikan beberapa tips untuk memulai dan menjaga rutinitas olahraga yang konsisten." },
        { type: "text", value: "Indulging in physical activity like sports improves your heart function, reduces the risks of diabetes, lowers tension and stress, and controls blood sugar." },
        { type: "heading", value: "Manfaat Kesehatan Fisik" },
        { type: "text", value: "Olahraga teratur membantu menjaga berat badan yang sehat, meningkatkan kekuatan dan kekuatan otot, serta meningkatkan kesehatan jantung dan sistem kardiovaskular." },
        { type: "text", value: "Aktivitas fisik juga dapat meningkatkan fleksibilitas, keseimbangan, dan koordinasi tubuh, yang semuanya penting untuk menjaga mobilitas dan mengurangi risiko cedera. Berikut adalah beberapa keunggulan yang lainnya:" },
        { type: "list", value: [
          "Meningkatkan kebugaran dan stamina: Melalui olahraga, tubuh dapat meningkatkan kebugaran dan stamina, sehingga individu mampu menjalani aktivitas sehari-hari dengan lebih mudah dan berenergi.",
          "Memperkuat otot dan tulang: Melakukan olahraga membantu memperkuat otot dan tulang, sehingga dapat mengurangi risiko cedera dan osteoporosis.",
          "Menjaga kesehatan jantung: Olahraga dapat menjaga kesehatan jantung dengan menurunkan tekanan darah, kolesterol, dan risiko penyakit jantung.",
          "Menurunkan berat badan: Dengan membakar kalori melalui olahraga, individu dapat menurunkan berat badan dan mengurangi risiko obesitas serta penyakit terkaitnya.",
          "Meningkatkan kualitas tidur: Melakukan olahraga secara teratur dapat membantu meningkatkan kualitas tidur, sehingga individu dapat tidur lebih nyenyak dan berkualitas.",
        ] },
        { type: "heading", value: "Manfaat Kesehatan Mental" },
        { type: "text", value: "Selain manfaat fisik, olahraga juga memiliki dampak positif pada kesehatan mental. Berolahraga secara teratur dapat mengurangi stres, kecemasan, dan depresi, serta meningkatkan suasana hati dan kesejahteraan emosional secara keseluruhan." },
        { type: "text", value: "Aktivitas fisik melepaskan endorfin, neurotransmiter alami yang dikenal sebagai “hormon bahagia,” yang dapat meningkatkan perasaan positif dan mengurangi rasa sakit. Berikut adalah beberapa manfaat untuk kesehatan mental: " },
        { type: "list", value: [
          "Mengurangi stres dan kecemasan: Melakukan olahraga dapat mengurangi tingkat stres dan kecemasan dengan meningkatkan produksi hormon endorfin yang dapat meningkatkan mood.",
          "Meningkatkan fokus dan konsentrasi: Olahraga membantu meningkatkan fokus dan konsentrasi dengan meningkatkan aliran darah ke otak, sehingga individu dapat lebih fokus dalam menjalani aktivitas sehari-hari.",
          "Meningkatkan kepercayaan diri: Melalui olahraga, individu dapat meningkatkan kepercayaan diri dengan memperbaiki citra tubuh dan kemampuan fisiknya.",
          "Meningkatkan kesehatan mental: Melakukan olahraga secara teratur dapat membantu meningkatkan kesehatan mental dengan mengurangi risiko depresi dan kecemasan.",
        ] },
        { type: "text", value: "Dengan memahami manfaat fisik dan mental dari olahraga, penting bagi individu untuk mengintegrasikan aktivitas ini ke dalam gaya hidup sehari-hari untuk menjaga kesehatan dan kesejahteraan secara keseluruhan." },
        { type: "heading", value: "Tips untuk Memulai Rutinitas Olahraga" },
        { type: "list", value: [
          "Pilih aktivitas yang Anda nikmati: Cari jenis olahraga atau aktivitas fisik yang sesuai dengan minat dan kemampuan Anda, apakah itu berjalan, berlari, bersepeda, atau berenang.",
          "Tetapkan tujuan yang realistis: Tentukan tujuan yang spesifik dan terukur untuk membantu Anda tetap termotivasi dan fokus dalam mencapai hasil yang diinginkan.",
          "Mulailah secara perlahan: Jangan terlalu berlebihan pada awalnya. Mulailah dengan intensitas dan durasi yang sesuai dengan tingkat kebugaran Anda saat ini, dan tingkatkan secara bertahap seiring waktu.",
          "Jadwalkan waktu untuk olahraga: Jadwalkan sesi olahraga Anda seperti janji penting lainnya dan lakukan secara teratur. Jadwalkan waktu yang tepat untuk berolahraga, apakah itu di pagi hari, siang, atau malam, sesuai dengan preferensi dan ketersediaan Anda.",
          "Temukan dukungan: Berolahraga dengan teman atau anggota keluarga dapat membuat pengalaman menjadi lebih menyenangkan dan memotivasi Anda untuk tetap konsisten.",
        ] },
        { type: "text", value: "Olahraga adalah investasi dalam kesehatan dan kesejahteraan kita. Dengan manfaatnya yang luas bagi kesehatan fisik dan mental, olahraga merupakan komponen penting dari gaya hidup sehat yang harus diprioritaskan." },
        { type: "text", value: "Dengan memulai dan menjaga rutinitas olahraga yang konsisten, kita dapat meningkatkan kualitas hidup kita dan mengurangi risiko penyakit jangka panjang. Jadi, mari bergerak, aktif, dan menjaga tubuh kita agar tetap sehat dan bugar untuk masa depan yang lebih baik." },
        { type: "text", value: "Exercise raises body temperature, improving sleep quality by lowering body temperature while sleeping. According to studies, exercising for at least 150 minutes a week can improve the quality of your sleep by up to 65%." },
      ]
    },
    3: {
      title: "Olahraga Ala Gen Z, 6 Tips Jogging Malam agar Tetap Bugar!",
      image: "https://cdn0-production-images-kly.akamaized.net/LHknvIuaUVDruyW-CSlFZKe-b70=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/5033268/original/087372100_1733205826-Depositphotos_177487308_S.jpg",
      content: [
        { type: "text", value: "Kesibukan sepanjang hari sering membuat banyak orang kesulitan meluangkan waktu untuk berolahraga. Padahal, aktivitas fisik secara teratur sangat penting untuk menjaga tubuh tetap sehat. Salah satu olahraga yang mudah dan praktis adalah jogging atau berlari santai. Menurut Healthline, manusia membutuhkan waktu selama 5-10 menit setiap hari untuk berlari demi menjaga kesehatan jantung." },
        { type: "text", value: "Maka dari itu, tren jogging pada malam hari akhir-akhir ini sedang ramai diperbincangkan, apalagi bagi kalangan Gen Z yang memiliki kesibukan saat pagi hingga sorenya. Olahraga ini dapat menjadi alternatif terbaik bagi kamu yang memiliki waktu luang hanya di waktu tertentu. Yuk, simak tips jogging di malam hari agar aktivitasmu lebih nyaman!" },
        { type: "heading", value: "1. Tentukan Jam yang Tepat Terlebih Dahulu" },
        { type: "image", value: "https://cdn1-production-images-kly.akamaized.net/Cg3UGK6wlEQn1bcpvfe_F5Mippc=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/5033269/original/055301300_1733205867-Olahraga_Ala_Gen_Z__6_Tips_Jogging_Malam_agar_Tetap_Bugar__1.jpg" },
        { type: "text", value: "Jika pada malam hari kamu merasa terlalu gelap, maka cobalah di jam-jam sebelum matahari terbenam. Contohnya seperti saat setelah pulang kerja. Kamu bisa luangkan sedikit waktu untuk berolahraga di luar sebelum benar-benar gelap. " },
        { type: "text", value: "Sore hari juga merupakan waktu yang ideal karena suhu biasanya lebih sejuk dan nyaman dibandingkan siang hari yang terik. Selain itu, jogging di waktu sore bisa jadi cara yang menyenangkan untuk melepas stres setelah seharian beraktivitas. Cobalah untuk jadikan ini sebagai rutinitas harian, dan nikmati suasana jogging yang lebih nyaman!" },
        { type: "heading", value: "2. Rencanakan Rute Jogging Sebelum Memulai" },
        { type: "image", value: "https://cdn1-production-images-kly.akamaized.net/1yDgsCIodDmlTBIKN_9gSGgMOhw=/640x853/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/5033271/original/003390900_1733205903-pexels-cottonbro-4543006.jpg" },
        { type: "text", value: "Selain menentukan waktu, kamu juga perlu untuk merencanakan rute jogging. Pilih rute jogging yang aman dan nyaman, misalnya taman kota atau area perumahan dengan pencahayaan yang cukup. Memilih rute yang familiar akan membuat olahraga lebih fokus tanpa rasa khawatir."},
        { type: "text", value: "Jika bosan dengan rute yang itu-itu terus, coba ganti rute sesekali dan gunakan aplikasi peta pada ponsel untuk memantau jarak serta lokasimu. Demi keamanan, beri tahu seseorang tentang rute dan waktu jogging kamu, terutama saat berolahraga sendirian."},
        { type: "heading", value: "3. Lakukan Pemanasan yang Cukup"},
        { type: "image", value:  "https://cdn1-production-images-kly.akamaized.net/j6QOtVkfASSZwxiwUn-OtvuLM1g=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/5033272/original/015029000_1733205936-Olahraga_Ala_Gen_Z__6_Tips_Jogging_Malam_agar_Tetap_Bugar__3.jpg"},
        { type: "text", value: "Suhu saat malam hari cenderung dingin dan sejuk, sehingga diperlukan pemanasan yang cukup untuk membuat keringat keluar sedikit terlebih dahulu. Suhu yang lebih dingin di malam hari memang membuat tubuh membutuhkan waktu lebih lama untuk siap bergerak." },
        { type: "text", value: "Lakukan pemanasan yang cukup, seperti stretching ringan atau jalan cepat, untuk memastikan otot-otot tidak tegang dan siap menghadapi aktivitas fisik. Pemanasan ini juga membantu aliran darah mengalir lebih lancar, sehingga kamu bisa berlari dengan nyaman dan mengurangi risiko cedera saat jogging." },
        { type: "heading", value: "4. Kenakan Pakaian yang Mudah Terlihat" },
        { type: "text", value: "Saat jogging di malam hari, memakai pakaian dengan warna cerah sangat penting agar kamu tetap terlihat oleh pejalan kaki dan pengendara. Pilih pakaian olahraga dengan strip atau detail yang akan memantulkan cahaya di sekitar. Dengan begitu, kamu bisa lebih aman saat menikmati waktu olahraga di malam hari." },
        { type: "text", value: "Selain itu, jangan lupa untuk membawa senter atau handphone untuk menyalakan lampu flash jika jogging di area yang minim pencahayaan. Ini tidak hanya membantu kamu melihat jalan lebih jelas, tapi juga membuatmu lebih mudah dikenali dari kejauhan, sehingga keamanan tetap terjaga selama berolahraga." },
        { type: "heading", value: "5. Bawa Air Putih yang Cukup" },
        { type: "text", value: "Meskipun udara malam terasa sejuk, tubuh tetap memerlukan cairan selama jogging, lho. Bawa air putih yang cukup agar tetap terhidrasi, karena tubuh tetap akan berkeringat saat berlari, apalagi jika durasinya cukup lama. " },
        { type: "text", value: "Minum air secara berkala sebelum, selama, dan sesudah berlari membantu menjaga energi dan mencegah rasa lelah berlebihan. Dengan tetap terhidrasi, kamu bisa menikmati aktivitas jogging malam tanpa khawatir merasa lemas. Jadi, jangan lupa untuk selalu bawa minum saat jogging di malam hari, ya!" },
        { type: "heading", value: "6. Coba Ajak Pasangan" },
        { type: "text", value: "Berlari bersama pasangan bisa jadi cara yang menyenangkan untuk tetap aktif sekaligus mempererat hubungan, lho. Dengan jogging bersama pasangan ini, motivasi untuk terus bergerak bisa lebih besar dan kamu bisa saling mendukung untuk mencapai target. Selain itu, lari bersama pasangan juga memberi kesempatan untuk berbicara dan menikmati waktu bersama, menjadikan aktivitas ini lebih menyenangkan dan penuh makna." },
        { type: "text", value: "Jadi, sehat bareng-bareng pasangan, deh. Menyenangkan, bukan? Yuk, coba ajak pasangan atau teman kamu untuk jogging bareng saat malam hari. Pasti pengalamannya lebih seru daripada olahraga sendirian." },
        { type: "text", value: "Itulah beberapa tips untuk jogging pada malam hari yang bisa kamu perhatikan sebelum berolahraga. Yuk, segera siapkan perlengkapanmu agar kamu bisa lebih menikmati lari malam yang menyenangkan dan pastinya menyehatkan!" },
      ]
    },
    4: {
      title: "The Top 5 Healthiest Foods for Kids", 
      image: "https://www.eatingwell.com/thmb/YxkWBfh2AvNYrDKoHukRdmRvD5U=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/article_291139_the-top-10-healthiest-foods-for-kids_-02-4b745e57928c4786a61b47d8ba920058.jpg",
      content: [
        { type: "text", value: "Anyone who's ever tried to feed a child (something other than cereal or ice cream) knows they don't always eat what you want. Trying to figure out what to make to nourish their tiny bodies is stressful. Plus, just because it gets served doesn't mean your kids will eat it. But kids need nutritious food—healthy fats for their brains, calcium for their bones and all the vitamins and minerals vegetables offer—and more." },
        { type: "text", value: "To take out some of the stress and make sure you're offering your child nutrient-dense foods, we compiled expert tips for mealtimes and a list of the top 10 healthy foods for kids. These foods are not only healthy for your kids (and for you!) but are also versatile and easy to prepare." },
        { type: "heading", value: "1. Yogurt" },
        { type: "image", value: "https://www.eatingwell.com/thmb/VYnzGHiEOIB7cPKWQZdTuhD5wXc=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/4559253-d51a3ac1d558422cac35f105d768ea7d.jpg" },
        { type: "text", value: "'Yogurt is a wonderful option for breakfast, a snack or even a dessert, but you have to watch the added sugar content',' says Katie Andrews, M.S., RD, a childhood nutrition coach and owner of Wellness by Katie. 'It's a healthy, filling snack that checks the boxes on protein and vitamin D, a nutrient many kids lack in their diet.' Be sure to check if the yogurt you buy has vitamin D because not all brands do. " },
        { type: "text", value: "Yogurt also delivers probiotics, good bacteria that are important for maintaining a healthy gut. Looking for an easy way to pick out a healthy yogurt? Buy plain Greek yogurt, which has zero added sugars plus twice the protein of regular yogurt. Most yogurt that's flavored has added sugar; some new products are flavored with just fruit, but plain is always a safe bet. It's easy to add flavor yourself by adding berries and sprinkling whole-grain cereal on top or creating a fun parfait with fruit. Dress up yogurt even more for kids by turning it into frozen yogurt pops or frozen yogurt bark." },
        { type: "heading", value: "2. Beans" },
        { type: "image", value: "https://www.eatingwell.com/thmb/25fWtClHrLmFM8GTyel2QG1VQxk=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/45650041-c60bb15137bd4228addb8d42afcc0c9f.jpg" },
        { type: "text", value: "Beans are a very nutritious food. They're loaded with protein and fiber, plus they're cheap and take little time to prepare. Buy low-sodium canned beans such as black beans, chickpeas or kidney beans. Simply open the can, rinse the beans to remove extra sodium and add to any dish."},
        { type: "text", value: "'Replacing ground beef with beans in a quesadilla or tossing beans with pasta helps maintain high-quality, lean protein while adding a key nutrient: fiber,' says Andrews."},
        { type: "text", value: "There are pastas made from beans too. 'Kids ages 4 to 8 need around 25 grams of fiber a day, and most products marketed directly to kids, like fruit snacks and cheese crackers, contain little if any. Fiber helps promote healthy digestion and helps your kids feel fuller longer, so they aren't asking you for a snack five minutes after dinner ends,' says Andrews."},
        { type: "heading", value: "3. Eggs"},
        { type: "image", value:  "https://www.eatingwell.com/thmb/hzFgREAGtQOc6J6YLPRb0FOTfmw=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/61836021-af3f0aaf6c85421d8bc2b1d4191ab4dc.jpg"},
        { type: "text", value: "One large egg has 6 g of protein and delivers vitamin D, vitamin B12 and iron, per the USDA. Some eggs are also fortified with omega-3 fatty acids, which aid in kids' brain development. Don't worry about the cholesterol—saturated and trans fats have a bigger impact on raising bad cholesterol than eggs." },
        { type: "text", value: "At breakfast, skip the pastries, fried foods and processed meats and scramble some eggs for your kids instead. If your kids aren't fans of scrambled, try different presentations like egg salad or egg casseroles." },
        { type: "text", value: "Eggs also make a great starter food for babies. Doctors used to recommend not giving eggs until babies were 12 months old. However, as of 2020, the American Academy of Allergy Asthma & Immunology states that allergenic foods like eggs can be introduced when babies are ready for solid foods, and in fact, might help prevent food allergies." },
        { type: "heading", value: "4. Avocado" },
        { type: "image", value: "https://www.eatingwell.com/thmb/88bJUmw13PE841aA_YpUh8UJf3g=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/6560934-7efd2ca090184d8c8b4a8d85be5fd9f8.jpg" },
        { type: "text", value: "Avocados are full of health benefits and are an easy way to get healthy fats into your child's diet. They are high in monounsaturated fats, which decrease inflammation and keep cholesterol levels healthy. Fat moves through the digestive tract slowly, so it keeps kids full longer. But the best part of avocados? Their versatility. You can eat them with a spoon, mash them on toast, throw them into a smoothie, mix them into chicken or tuna salad or make a pasta sauce like avocado pesto." },
        { type: "heading", value: "5. Sweet Potato" },
        { type: "text", value: "Short on time and need something nutritious? Wash a sweet potato, poke some holes in it and microwave it for 3-5 minutes (depending on its size). Slice it lengthwise, let it cool, then scoop it onto your child's plate." },
        { type: "text", value: "Whether your kid is 6 months old, 6 years old or 16 years old, sweet potatoes are appealing across the board (because they're sweet!). They're packed with beta carotene that the body uses to make vitamin A, fiber and potassium, per the USDA. Adequate potassium intake keeps blood pressure and hearts healthy." },
        ]
    },
    5: {
      title: "Healthy Food or Fast Food Which One Will You Choose for Your Daily Food? ",
      image: "https://assets.kompasiana.com/items/category/25-1628766518.jpg?t=o&v=770",
      content: [
        { type: "text", value: "In modern times like today, we are given a lot of choices when it comes to doing everything including food. As we know today in Indonesia there are many fast food outlets. The main reason for a large number of fast food outlets in Indonesia today is of course none other than a large number of consumers." },
        { type: "text", value: "It is undeniable that fast food is loved by many people because of its fast presentation and good taste. But in the midst of the phenomenon of the proliferation of fast food outlets, we must not forget that the food we consume will greatly affect our body." },
        { type: "text", value: "In the midst of very busy daily activities, eating healthy and nutritious food is very important and should not be missed. Because by eating healthy foods that are rich in vitamins, minerals, protein, calcium and so on will be very good for our bodies." },
        { type: "text", value: "To get healthy food is also not difficult, you can find various kinds of vegetables and fruits in the traditional market or supermarket. Foods such as vegetables cooked at home are certainly nutritious. And again cooking vegetables is not difficult, even some vegetables can also be eaten raw." },
        { type: "text", value: "By starting to eat healthy foods such as vegetables and fruit from now on, you can get a healthier and fitter body. This is due to the various vitamins and nutrients contained in these healthy foods. But don't forget you also have to accompany it with regular exercise, to get maximum results." },
        { type: "text", value: "Besides being able to make the body fitter, healthy food can also boost immunity. This was conveyed by a Nutritionist at Gadjah Mada University, Dr. Toto Sudargo., SKM., M.Kes, namely 'The high nutritional value of the food we consume can protect the body from viruses and allergies'." },
        { type: "text", value: "And on the contrary, it is different from healthy food which is highly recommended for daily consumption. Fast food is a food that is not recommended to be consumed too often especially every day. Because eating too much fast food can have a bad impact on your health." },
        { type: "text", value: "Of course, we know that until now there have been lots of people who have diabetes because they eat fast food too often. In addition to diabetes, there are various diseases caused by consuming too much fast food, such as stroke, hypertension, heart disease, and many more." },
        { type: "text", value: "The bad impact of consuming fast food is caused by the preservatives in it. In addition, generally fast food has very high fat and sugar content, and this is certainly very bad for our health." },
        { type: "text", value: "Judging from the explanation above, it is clear that eating healthy foods such as vegetables and fruit is much better than fast food. Especially if you cook these healthy foods yourself at home, of course, you will know for sure what compositions are in them. After learning about the difference between healthy food and fast food it is very clearly unbalanced. Healthy food is the best choice for your daily diet and for the health of your body." },
        { type: "text", value: "So don't hesitate to start eating healthy foods from now on, and get a healthy and fit body. Because according to the motto of an ancient roman poet that we all know 'Mens sana in corpore sano' that means in a healthy body there is a strong soul." },
        ]
    },
    6: {
      title: "3 Makanan Sehat Ini Bisa Jadi Camilan Favoritmu Saat Bersantai di Rumah", 
      image: "https://cdn0-production-images-kly.akamaized.net/CGxw9otAzhT_oWkxEInFUXVicUQ=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3141793/original/033147400_1591086738-woman-in-yellow-sweater-holding-white-ceramic-plate-3886026.jpg",
      content: [
        { type: "text", value: "Camilan menjadi menu yang wajib ada di ruang tamu saat kita menikmati momen santai di rumah. Kebanyakan orang akan memilih makanan fast food ataupun snack ringan untuk dijadikan camilan andalan anti ribet." },
        { type: "text", value: "Tapi makanan atau camilan yang kamu konsumsi sebenarnya kurang sehat untuk tubuh. Camilan ringan yang kamu konsumsi sehari-hari tersebut bahkan bisa menjadi salah satu penyebab obesitas jika kamu tidak mengontrolnya atau menggantinya dengan camilan yang lebih sehat. Memang benar, rasa dari makanan fast food atau jajanan seperti snack-snack berbungkus memang menggiurkan, kamu boleh sesekali memakannya tetapi jelas tidak untuk konsumsi berlebihan sehari-hari." },
        { type: "text", value: "Hidup dengan pola makan sehat memang tidak mudah, tetapi bisa kamu mulai dengan mengganti camilan ringanmu dengan makanan yang jauh lebih sehat. Secara tekstur dan rasa pasti kalah tetapi demi kesehatan tubuh, kamu sebaiknya tidak boleh kompromi." },
        { type: "text", value: "Nah, buat kamu yang kini punya banyak waktu bersantai dan punya hobi mengemil, sebaiknya perlu mengganti camilanmu dengan rekomendasi makanan sehat berikut, Fimela.com akan membgikan informasi 3 makanan sehat yang bisa kamu jadikan Camilan sehari-hari. Simak selengkapnya dibawah ini." },
        { type: "heading", value: "Pudding atau Agar-Agar" },
        { type: "image", value: "https://cdn1-production-images-kly.akamaized.net/Q1krE8tWWjt4y9-eEAlrpoA1Bzs=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3141803/original/022474100_1591088270-flan-creme-caramel-dessert_82893-12538.jpg" },
        { type: "text", value: "Makanan sehat yang bisa kamu jadikan camilan sehari-hari ialah pudding dan agar-agar. Kedua makanan ini memiliki tekstur yang hampir mirip, hanya biasanya pudding disajikan dengan banyak topping atau dikombinasikan dengan bahan lain seperti remahan biskuit atau roti misalnya." },
        { type: "text", value: "Baik pudding maupun agar-agar merupakan makanan sehat yang ringan untuk kamu konsumsi dan sudah pasti cocok untuk menjadi pengganti camilanmu yang sebelumnya kurang sehat. Tidak perlu khawatir karena kamu bisa membuatnya di rumah dengan praktis karena kedua makanan tersebut sudah tersedia produk instannya." },
        { type: "text", value: "Kamu harus tahu bahwa pudding dan agar-agar memiliki nutrisi baik yang dibutuhkan oleh tubuh seperti vitamin, kalsium, mineral, bahkan serat. Buat kamu yang jarang mengkonsumsi buah, agar-agar bisa menjadi alternatif bagi tubuhmu untuk tetap mendapatkan serat. Manfaat serat dalam tubuh dapat membuat pencernaanmu menjadi sehat dan lancar." },
        { type: "heading", value: "Salad Buah" },
        { type: "image", value: "https://cdn0-production-images-kly.akamaized.net/wzJ_JoHpjUMxiMbaxGISRGoBFVY=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3141804/original/035390300_1591088270-bowl-of-vegetable-salad-and-fruits-936611__1_.jpg" },
        { type: "text", value: "Selanjutnya, makanan sehat yang bisa kamu jadikan camilan ialah salad buah, tentu kamu pasti akan menyukainya. Bisa dikatakan bahwa salad buah adalah pilihan terbaik untuk mengganti camilan fast food yang biasanya kamu makan. Ditambah lagi kini salad buah sendiri memang sedang populer dan banyak produsen yang menjualnya." },
        { type: "text", value: "Soal manfaatnya untuk kesehatan tubuh sudah tidak perlu dipertanyakan lagi, salad buah sesuai namanya terdiri dari berbagai macam buah-buahan segar. Mulai dari semangka, manga, apel, jeruk, kiwi, hingga strawberry. Hanya dengan menyebut komposisi buahnya saja, kamu pasti sudah bisa membayangkan betapa segarnya salad buah." },
        { type: "text", value: "Salad buah sendiri juga kini mudah kamu dapatkan dengan berbagai macam varian, misal mulai dari salad buah plain sampai salad buah yang menggunakan berbagai topping seperti keju dan coklat. Pastinya salad buah akan menjadi camilan sehat yang bisa meningkatkan mood-mu juga." },
        { type: "heading", value: "Telur Rebus" },
        { type: "image", value: "https://cdn1-production-images-kly.akamaized.net/RzQ_CAv5uZQX2a-1J5CMD33XKqg=/0x119:4016x2382/640x360/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/3141805/original/026080400_1591088271-8366.jpg" },
        { type: "text", value: "Berikutnya, jika kamu tidak begitu tertarik dengan camilan yang memiliki cita rasa manis, kamu bisa memilih telur rebus sebagai camilan sehatmu, Telur merupakan camilan yang paling sehat terutama jika kamu sedang menjalani program diet. Telur rebus juga memiliki banyak kandungan gizi yang sangat bermanfaat untuk tubuh." },
        { type: "text", value: "Sebut saja protein serta vitamin K2 dan B12 yang terkandung didalam telur rebus merupakan gizi yang dibutuhkan oleh tubuh. Mengonsumsi telur rebus juga membuatmu merasa kenyang lebih lama sehingga mengurangi keinginanmu untuk terus makan lebih banyak." },
        { type: "text", value: "Cara membuatnya juga sangat mudah, kamu hanya perlu merebusnya saja dalam waktu belasan menit. Sesudahnya kupas kulit telur tersebut dan sajikan selagi masih hangat. Tidak perlu khawatir dengan baunya, telur yang sudah direbus tidak akan terlalu amis." },
        ]
    },
    7: {
      title: "5 tips to boost your mental health", 
      image: "https://www.bcmhsus.ca/sites/g/files/qpdaav151/files/styles/landscape_840x450_2x/public/media/10_tips_website.png.jpg?itok=LGXOENE-",
      content: [ 
      { type: "text", value: "​'Mental health' refers to your overall psychological well-being. It includes the way you feel about yourself, the quality of your relationships, and your ability to manage your feelings and deal with difficulties." },
      { type: "text", value: "Anyone can experience mental or emotional health problems — and over a lifetime, many of us will. According to the Centre for Addiction and Mental Health, one in five Canadians experiences a mental illness in any given year. And by the time Canadians reach 40 years old, one in two people have, or have had, a mental illness." },
      { type: "text", value: "While they're not substitutes for advice or care from qualified health professionals (see the end of the article for programs and resources), these tips can help you elevate your mood, become more resilient and enjoy life more." },
      { type: "heading", value: "1. Make social connection — especially face-to-face — a priority" },
      { type: "text", value: "Phone calls and social networks have their place, but few things can beat the stress-busting, mood-boosting power of quality face-to-face time with other people, especially those you love and people who energize you. For several years, COVID-19 significantly limited this opportunity, however as restrictions continue to lift, this may be a good time to rebuild safe in-person interactions." },
      { type: "heading", value: "2. Stay active" },
      { type: "text", value: "Staying active is as good for the brain as it is for the body. Regular exercise or activity can have a major impact on your mental and emotional health, relieve stress, improve memory, and help you sleep better." },
      { type: "heading", value: "3. Talk to someone" },
      { type: "text", value: "Talk to a friendly face. If you have concerns, stresses or worries, sharing these with someone who cares is one of the most effective ways to calm your nervous system and relieve stress. And vice versa: Sometimes listening to others in a safe and supported way can help you develop wider perspectives. It is important that both parties feel comfortable to share and hear each other's thoughts, and if the worries are beyond this, consider speaking to a professional (see programs and resources at the end of the article)." },
      { type: "heading", value: "4. Appeal to your senses" },
      { type: "text", value: "Does listening to an uplifting song make you feel calm? Does squeezing a stress ball help you feel centred? What about taking a walk in nature and enjoying the sights and sounds of the trees? Everyone responds to sensory input a little differently, so experiment with healthy sensory inputs (rather than unhealthy sensory inputs) to find what works best for you." },
      { type: "heading", value: "5. Take up a relaxation practice" },
      { type: "text", value: "Yoga, mindfulness, meditation and deep breathing can help reduce overall levels of stress." },
      ]
    },
    8: {
      title: "Our best mental health tips - backed by research", 
      image: "https://www.mentalhealth.org.uk/sites/default/files/styles/750_x_450_mhf_theme/public/2024-08/Best%20MH%20tips%20website%20teaser.png?h=10d202d3&itok=_ypSspNn",
      content: [
        { type: "heading", value: "1. Get closer to nature" },
        { type: "text", value: "We all live with worries and fears, uncertainties, losses that leave us sad and pressures that make us feel stressed. Nature can have a really calming effect on us." },
        { type: "text", value: "We have been living around other animals and plants for thousands of years. Some people say nature helps them feel calmer, more hopeful and less alone. Our research found that going for a walk was UK adults’ favourite way of coping with stress during the pandemic in 2020." },
        { type: "text", value: "In Japan, some people do “forest bathing”, which may improve their mental health. So going to a forest or wood and experiencing the different smells, sounds and textures may really help." },
        { type: "text", value: "To get the best out of nature’s healing effects, try tuning your senses to what’s around you – the trees, plants, birds and animals, for instance, and water such as ponds or the seashore. " },
        { type: "text", value: "Take a deep breath and see how you feel. The idea is to get connected with your natural surroundings." },
        { type: "heading", value: "2. Get more from your sleep" },
        { type: "text", value: "Anyone who has struggled with sleep will know what a difference it makes to our bodies, minds and ability to cope with life. We all have times when we sleep badly, and some of us live in situations that make a good night’s sleep impossible." },
        { type: "text", value: "For many people, sleep is often the first thing that suffers when we're struggling with our mental health. Adults need between 7 and 9 hours' sleep a night, including enough dreaming sleep and enough deeper sleep. If you’re struggling with your sleep, think about trying a few simple changes." },
        { type: "heading", value: "3. Keep moving" },
        { type: "text", value: "Our bodies and minds are connected, so looking after ourselves physically also helps us prevent problems with our mental health (it works the other way around, too)." },
        { type: "text", value: "Moving our bodies – with sport, gardening, dancing, cycling, walking the dog, cleaning or going to the gym, for example – are great ways to improve our mental and physical health." },
        { type: "text", value: "Exercise releases “feel good” hormones that reduce feelings of stress and anger. It also helps us feel better about our bodies. It can improve our sleep too. If it involves other people, like being part of a team, a class or a group we see regularly, that can also boost our mental health." },
        { type: "text", value: "We don’t have to be professional athletes, or sporty, to get the benefits of being physically active. From walking to dancing and basketball to the gym, the best exercise is simply the one we enjoy." },
      ]
    },
    9: {
      title: "The Importance of Mental Health: Tips and Tricks",
      image: "https://www.verywellmind.com/thmb/KcAt1iT48tlfgmQhsxfrcoU0e08=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/GettyImages-1297758187-f4fda9215edc4b7ba0040dbb77d970e9.jpg",
      content: [
        { type: "text", value: "Your mental health is an important part of your well-being. This aspect of your welfare determines how you’re able to operate psychologically, emotionally, and socially among others." },
        { type: "text", value: "Considering how much of a role your mental health plays in each aspect of your life, it's important to guard and improve psychological wellness using appropriate measures." },
        { type: "text", value: "Because different circumstances can affect your mental health, we’ll be highlighting risk factors and signs that may indicate mental distress. But most importantly, we’ll dive into why mental health is so important." },
        { type: "heading", value: "Risk Factors for Poor Mental Health" },
        { type: "text", value: "Mental health is described as a state of well-being where a person is able to cope with the normal stresses of life. This state permits productive work output and allows for meaningful contributions to society." },
        { type: "text", value: "However, different circumstances exist that may affect the ability to handle life’s curveballs. These factors may also disrupt daily activities, and the capacity to manage these changes. That's only one reason why mental health is so important." },
        { type: "text", value: "The following factors, listed below, may affect mental well-being and could increase the risk of developing psychological disorders." },
        { type: "heading", value: "Childhood Abuse" },
        { type: "text", value: "Childhood physical assault, sexual violence, emotional abuse, or neglect can lead to severe mental and emotional distress. Abuse increases the risk of developing mental disorders like depression, anxiety, post-traumatic stress disorder, or personality disorders." },
        { type: "text", value: "Children who have been abused may eventually deal with alcohol and substance use issues. But beyond mental health challenges, child abuse may also lead to medical complications such as diabetes, stroke, and other forms of heart disease." },
        { type: "heading", value: "The Environment" },
        { type: "text", value: "A strong contributor to mental well-being is the state of a person’s usual environment. Adverse environmental circumstances can cause negative effects on psychological wellness." },
        { type: "text", value: "For instance, weather conditions may influence an increase in suicide cases. Likewise, experiencing natural disasters firsthand can increase the chances of developing PTSD. In certain cases, air pollution may produce negative effects on depression symptoms." },
        { type: "text", value: "In contrast, living in a positive social environment can provide protection against mental challenges." },
        { type: "heading", value: "Biology" },
        { type: "text", value: "Your biological makeup could determine the state of your well-being. A number of mental health disorders have been found to run in families and may be passed down to members." },
        { type: "text", value: "These include conditions such as autism, attention deficit hyperactivity disorder, bipolar disorder, depression, and schizophrenia." },
        { type: "heading", value: "Lifestyle" },
        { type: "text", value: "Your lifestyle can also impact your mental health. Smoking, a poor diet, alcohol consumption, substance use, and risky sexual behavior may cause psychological harm. These behaviors have been linked to depression." },
      ]
    },
    10: {
      title: "Pilihan Aksesori untuk Menambah Gaya Modis, Mana Favoritmu?", 
      image: "https://cdn0-production-images-kly.akamaized.net/uuV8dzLHqFEMi201p8uoF7GGIWs=/1x70:1000x633/640x360/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4990101/original/083390700_1730710641-Depositphotos_131619278_S.jpg",
      content: [
        { type: "text", value: "Aksesori adalah elemen penting dalam dunia fashion yang dapat mengubah tampilan seseorang secara signifikan. Dari kalung yang sederhana hingga tas yang mencolok, aksesori menawarkan cara yang mudah dan efektif untuk mengekspresikan kepribadian serta gaya pribadi. Mereka tidak hanya menambah daya tarik visual tetapi juga memberikan sentuhan akhir yang sempurna pada setiap penampilan." },
        { type: "text", value: "Dalam dunia mode yang terus berkembang, memiliki aksesori yang tepat bisa menjadi kunci untuk tampil lebih maksimal tanpa banyak usaha. Jika Anda ingin meningkatkan gaya Anda dan membuat pernyataan yang kuat melalui penampilan, memilih aksesori yang tepat adalah langkah yang bijak. Beberapa pelengkap ini tidak hanya wajib dimiliki tetapi juga dapat menyempurnakan setiap penampilan, baik untuk acara formal maupun kasual." },
        { type: "heading", value: "1. Arloji" },
        { type: "image", value: "https://cdn0-production-images-kly.akamaized.net/0oYjhm0Z9bKkB-zMQv8JgLbO8Hc=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4990115/original/094030500_1730711214-pexels-the-5th-50003-179909.jpg" },
        { type: "text", value: "Jam tangan bukan hanya alat penunjuk waktu, tetapi juga mencerminkan gaya pribadi. Pilihlah desain yang klasik dan abadi agar dapat dipadukan dengan berbagai busana, baik untuk acara formal maupun santai. Untuk tampilan formal, jam tangan berbahan stainless steel atau kulit dengan dial berwarna gelap dan desain klasik sangat serbaguna. Jika ingin tampil kasual, pilih jam tangan dengan tali kain atau karet berdesain sederhana yang cocok dipadukan dengan kaos dan jeans." },
        { type: "heading", value: "2. Sunglasses atau Kacamata Hitam" },
        { type: "image", value: "https://cdn1-production-images-kly.akamaized.net/pJkrJOC7Q5CyhKIvwtiU4JNo-fg=/640x360/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4990116/original/005132600_1730711249-pexels-cottonbro-6069089.jpg" },
        { type: "text", value: "Kacamata hitam dapat dengan mudah membuat penampilan lebih modis dalam waktu singkat. Selain berfungsi melindungi mata dari sinar UV, kacamata hitam dengan bingkai unik dapat menjadi bagian penting yang menambah karakter pada gaya Anda. Kacamata dengan desain sederhana dan bingkai tipis memberikan kesan modern. Pilihan ini cocok untuk tampilan kasual atau semi-formal, menambahkan detail tanpa terlihat mencolok." },
        { type: "heading", value: "3. Tas Mini atau Tas Selempang" },
        { type: "image", value: "https://cdn0-production-images-kly.akamaized.net/v_OJMMxLj3rI6SQ4ZWpom3eYnlQ=/640x853/smart/filters:quality(75):strip_icc():format(webp)/kly-media-production/medias/4990119/original/057161200_1730711320-pexels-chickenbunny-102941452-9463092.jpg" },
        { type: "text", value: "Tas kecil yang fungsional dan modis bisa menjadi solusi ketika kamu ingin tampil simpel namun tetap bergaya. Tas ini tidak hanya memudahkan dalam membawa barang-barang, tetapi juga dapat meningkatkan keseluruhan penampilanmu." },
        { type: "text", value: "Crossbody bag dengan warna netral adalah pilihan yang aman, tetapi jika ingin tampil lebih berani, cobalah memilih warna atau motif yang lebih mencolok. Selain crossbody bag, mini backpack juga bisa menjadi pilihan yang sporty dan chic. Tas ini menawarkan ruang yang lebih luas, cocok untuk jalan-jalan atau berlibur" },
      ]
    },
    11: {
      title: "Tren Fashion Jepang Terbaru yang Wajib Anda Coba!", 
      image: "https://www.abyadscreenprinting.com/wp-content/uploads/2024/01/fashion-japan-style.jpeg",
      content: [ 
        { type: "text", value: "Asia memiliki beberapa pusat fashion yang kini dijadikan kiblat dunia, salah satu yang terbesar adalah Jepang. Lebih membuka diri di Era Meiji (sekitar tahun 1868-1912) Jepang telah mulai menyerap budaya dari luar, termasuk Barat. Seiring berjalannya waktu, Negeri Sakura ini memiliki gaya mereka tersendiri dan berkembang hingga sekarang. " },
        { type: "heading", value: "Gaya Fashion Jepang" },
        { type: "text", value: "Beberapa akan dengan mudah mengenali bahwa Harajuku merupakan salah satu gaya fashion paling terkenal di Jepang. Selain itu, beberapa gaya di bawah ini juga menjadi alasan Jepang kini dikenal sebagai pusat fashion dunia. " },
        { type: "heading", value: "1. Yukata Modern" },
        { type: "text", value: "Pada awalnya, Yukata hanya digunakan di pemandian-pemandian karena mampu menyerap air. Namun, dalam perkembangannya, Yukata digunakan sebagai pakaian keseharian, terutama ketika musim panas berlangsung. Kini, Yukata juga dipadukan dengan gaya lebih modern. " },
        { type: "text", value: "Jika Anda ingin menjajal Yukata sebagai gaya fashion terbaru Anda, beberapa tips di bawah ini perlu untuk dilakukan. Bila Anda wanita dengan postur tubuh tinggi, pilih pola yang lucu, halus, dan lembut. Bila Anda berkulit putih, Yukata cerah akan membuat tampilan kulit lebih cerah, dan jika kulit Anda cenderung gelap, warna-warna dalam seperti nila akan lebih cocok. Jika Anda pria, hindari warna Yukata yang mencolok dan pola rumit. " },
        { type: "image", value: "https://i0.wp.com/www.abyadscreenprinting.com/wp-content/uploads/2024/01/Yukata-Modern-cewek.jpeg?w=334&ssl=1" },
        { type: "heading", value: "2. Kimono dengan Sentuhan Kontemporer" },
        { type: "text", value: "Sekarang ini, Kimono juga telah banyak tersentuh oleh dunia modern. Kimono modern biasanya memiliki corak dan motif yang tidak terdapat di jenis tradisional, seperti motif polkadot, bunga mawar, dan sebagainya. Dahulu, Kimono menggunakan warna seperti sakura (sakura-iro) atau warna merah muda terang maupun warna biru keunguan (ruri-iro). " },
        { type: "text", value: "Perbedaan lain dari Kimono modern dengan tradisional juga dari bahan yang digunakan. Jika Kimono tradisional terbuat dari sutra yang notabene lebih mahal. Maka Kimono modern juga terkadang dibuat dengan bahan katun, polyester, hingga denim yang tentu lebih miring dan mudah dicuci, meski menggunakan mesin cuci. " },
        { type: "image", value: "https://i0.wp.com/www.abyadscreenprinting.com/wp-content/uploads/2024/01/Kimono-dengan-Sentuhan-Kontemporer.jpeg?w=380&ssl=1" },
        { type: "text", value: "Jika Anda ingin menjajal Kimono, ada baiknya untuk memilih jenis yang memang cocok. Siapakah Anda? Apakah Anda adalah wanita berpostur tinggi atau cenderung pendek? Apakah warna kulit Anda cenderung putih atau lebih gelap?  Pertimbangan tersebut perlu dilakukan. Sebab, salah-salah memilih warna, motif, bahkan aksesoris yang digunakan akan membuat tampilan Anda malah menjadi kurang menarik." },
        { type: "heading", value: "3. Gaya Harajuku" },
        { type: "text", value: "Meski sebenarnya merupakan nama tempat di Distrik Shibuya, Harajuku lebih dikenal sebagai salah satu gaya fashion dari Jepang yang juga mendunia. Harajuku memiliki beberapa macam dan jenis fashion lagi, mulai dari cosplay, Lolita, punk, gyaru, ganguro, yamanba atau manba, dan visual kei." },
        { type: "image", value: "https://i0.wp.com/www.abyadscreenprinting.com/wp-content/uploads/2024/01/Gaya-Harajuku.jpeg?w=473&ssl=1" },
        { type: "text", value: "Salah satu ciri khas Harajuku adalah gaya yang lebih beragam dan kreatif, seperti memadukan warna-warni aksesoris yang mencolok. " },
        { type: "text", value: "Cara memadupadankan sytle Harajuku juga terbilang unik, seperti ripped jeans dengan t-shirt oversized, jaket dengan mini skirt, gothic looks yang identik dengan warna gelap, atau bisa juga dengan gaya t-shirt dan celana yang sama-sama mencolok." },
      ]
    },
    12: {
      title: "Sejarah Prancis untuk Menjadi Titik Utama Fashion Dunia", 
      image: "http://student-activity.binus.ac.id/himhi/wp-content/uploads/sites/42/2020/12/d684c718-4d9b-429f-b098-13429352f89d.jpg",
      content: [
        { type: "text", value: "Prancis dikenal dengan banyak hal, seperti makanannya yang enak, pemandangannya yang indah, dan tentunya trend fashion mereka. Masyarakat Prancis bisa dikatakan berhutang kecantikan asli mereka kepada Raja Louis XIV, ‘Raja Matahari‘ yang pemerintahannya dimulai pada tahun 1643. Louis memiliki selera yang sangat mewah, terbukti dari Istana Versailles yang spektakuler (perluasan yang dia perintahkan) serta cara ia berpakaian." },
        { type: "text", value: "Selama berabad-abad yang akan datang, kain dan bahan dengan kualitas terbaik dapat ditemukan di Prancis. Industri mode Prancis menurun secara signifikan selama Perang Dunia Kedua. Di bawah pendudukan Nazi, toko Chanel terpaksa ditutup, bersama dengan beberapa maisons de couture lainnya. AS memanfaatkan kesempatan ini untuk membangun kehadiran busana sendiri, mengalihkan perhatian pers ke desainer Amerika seperti Claire McCardell." },
        { type: "text", value: "Setelah bertahun-tahun penjatahan ketat dan kekurangan tekstil, kebangkitan industri pakaian akan dibawa oleh seorang visioner Prancis lainnya. Christian Dior mulai mendominasi mode pasca-perang dengan apa yang kemudian dikenal sebagai ‘tampilan baru.’ Ditandai dengan pinggang yang menjepit dan rok A-line yang jatuh hingga pertengahan betis." },
        { type: "text", value: "‘Tampilan baru’ ini dibuat untuk menampilkan tampilan yang feminin dan elegan. Di abad ke-20, masyarakat menyaksikan sejumlah besar desainer yang mulai bermunculan. Di Paris, orang-orang seperti Hubert de Givenchy dan Pierre Balmain muncul, keduanya mempertahankan reputasi industri mode Prancis yang dulu pudar." },
        { type: "text", value: "Hingga saat ini, Paris tetap menjadi ibu kota mode resmi, bersama Milan, New York dan London, serta semakin banyak kota yang ingin memperkuat kehadiran mereka di industri – terutama Barcelona, Berlin, dan Singapura. Terlepas dari tingkat persaingan yang cukup tinggi dari kota-kota ini, mode adalah aspek yang mengakar dalam budaya Prancis dan profil internasionalnya – dan kemungkinan besar akan selalu demikian. Dengan alasan tersebut, bisa dikatakan Prancis sangatlah mempegaruhi mode atau cara berpakaian masyarakat internasional." },
      ]
    },
  };


  const params = new URLSearchParams($location.absUrl().split('?')[1]);
  const articleId = parseInt(params.get('id'), 10);


  $scope.article = articles[articleId];
});
